name: base
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anaconda-anon-usage=0.4.4=py312hfc23b7f_100
  - anaconda_powershell_prompt=1.1.0=haa95532_0
  - anaconda_prompt=1.1.0=haa95532_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - boltons=23.0.0=py312haa95532_0
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py312h827c3e9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.3=pyhe01879c_0
  - conda=24.11.3=py312h2e8e312_0
  - conda-content-trust=0.2.0=py312haa95532_1
  - conda-libmamba-solver=24.9.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py312haa95532_0
  - conda-package-streaming=0.10.0=py312haa95532_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - cryptography=43.0.0=py312h89fc84f_0
  - debugpy=1.8.17=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=py312haa95532_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.6.3=h5da7b33_0
  - fmt=9.1.0=h6d14046_1
  - frozendict=2.4.2=py312haa95532_0
  - idna=3.7=py312haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jsonpatch=1.33=py312haa95532_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libarchive=3.7.4=h9243413_0
  - libcurl=8.9.1=h0416ee5_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libiconv=1.16=h2bbff1b_3
  - libmamba=1.5.8=h99b1521_3
  - libmambapy=1.5.8=py312h77c03ed_3
  - libsodium=1.0.20=hc70643c_0
  - libsolv=0.7.24=h23ce68f_1
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.0=h291bd65_0
  - libxml2=2.13.1=h24da03e_2
  - libzlib=1.2.13=h2466b09_6
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - menuinst=2.1.2=py312h5da7b33_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h725018a_0
  - packaging=24.1=py312haa95532_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=py312haa95532_0
  - platformdirs=3.10.0=py312haa95532_0
  - pluggy=1.0.0=py312haa95532_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py312he06e257_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h2bbff1b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.3=h2628c8c_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=8_cp312
  - pywin32=311=py312h829343e_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.3=py312haa95532_0
  - ruamel.yaml=0.18.6=py312h827c3e9_0
  - ruamel.yaml.clib=0.2.8=py312h827c3e9_0
  - setuptools=75.1.0=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h0416ee5_0
  - tornado=6.5.2=py312he06e257_1
  - tqdm=4.66.5=py312hfc267ef_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.8.0=py312haa95532_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2024b=h04d1e81_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.2.3=py312haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.44.0=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml-cpp=0.8.0=hd77b12b_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h2466b09_6
  - zstandard=0.23.0=py312h4fc1ca9_0
  - zstd=1.5.6=h8880b57_0
prefix: C:\Users\Yuuni\miniconda3
