name: emergab
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.9.23
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.0
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.3
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.9.25
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  # - pywin32=311
  - pyzmq=27.0.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  # - ucrt=10.0.22621.0
  # - vc=14.3
  # - vc14_runtime=14.44.35208
  # - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses==0.6
      - editdistance==0.8.1
      - egg==0.1.0
      - eval-type-backport==0.3.1
      - exceptiongroup==1.3.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.1
      - idna==3.11
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lightning-utilities==0.15.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.23.5
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - protobuf==6.33.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pytest==8.4.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - submitit==1.5.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tomli==2.3.0
      - torch==2.8.0
      - torchmetrics==1.8.2
      - torchvision==0.23.0
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.1
      - wandb==0.23.1
# prefix: C:\Users\Yuuni\miniconda3\envs\emergab
